<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CMMN" nsURI="https://org/eclipse/cmmnmetamodel" nsPrefix="org.eclipse.emfcloud.cmmn.metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="CMMNDiagram" eSuperTypes="#//CMMNElement">
    <eOperations name="duplicateNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmmnElements" lowerBound="1"
        upperBound="-1" eType="#//CMMNElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseFile" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String256chars"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//CMMNElement">
    <eOperations name="duplicateStageNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="duplicateTaskNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="casefile" lowerBound="1"
        eType="#//CaseFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" lowerBound="1"
        upperBound="-1" eType="#//Stage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String100Chars"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventListeners" upperBound="-1"
        eType="#//EventListener" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" eSuperTypes="#//PlanItemDefinition">
    <eOperations name="duplicateNames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String100Chars"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventListeners" upperBound="-1"
        eType="#//EventListener" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//PlanItemDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskType" eType="#//TaskType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskRole" eType="#//TaskRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String256chars"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventListener" eSuperTypes="#//PlanItemDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//String256chars"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sentry" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifPart" eType="#//IfCondition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SentryType" eType="#//SentryType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onPart" lowerBound="1"
        eType="#//PlanItemDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anchor" lowerBound="1"
        eType="#//PlanItemDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskRole">
    <eLiterals name="Human"/>
    <eLiterals name="Process" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskType">
    <eLiterals name="Task"/>
    <eLiterals name="DiscretionaryTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SentryType">
    <eLiterals name="Entry"/>
    <eLiterals name="Exit" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlanItemDefinition" eSuperTypes="#//CMMNElement">
    <eOperations name="isUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="isNoCircle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingSentrys" upperBound="-1"
        eType="#//Sentry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorators" upperBound="-1"
        eType="#//Decorator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingSentrys" upperBound="-1"
        eType="#//Sentry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimerEventListener" eSuperTypes="#//EventListener">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//TimerExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserEventListener" eSuperTypes="#//EventListener"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimerExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decorator" eSuperTypes="#//CMMNElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MandatoryDecorator" eSuperTypes="#//Decorator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTPHookDecorator" eSuperTypes="#//Decorator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//URLFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="request" eType="#//StringHttpRequest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String100Chars" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxLength" value="100"/>
      <details key="pattern" value="[a-zA-Z0-9%20/]+"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="String256chars" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxLength" value="256"/>
      <details key="pattern" value="[a-zA-Z0-9%20/]+"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URLFormat" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value="[hH][tT]{2}[pP]://[wW]{3}.*"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IfCondition" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="pattern" value="[a-zA-Z0-9%20/]+[&lt;>=][a-zA-Z0-9%20/]+[\+\-*/]*[a-zA-Z0-9%20/]*"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HTTPRequest">
    <eLiterals name="GET"/>
    <eLiterals name="HEAD"/>
    <eLiterals name="POST"/>
    <eLiterals name="PUT"/>
    <eLiterals name="DELETE"/>
    <eLiterals name="CONNECT"/>
    <eLiterals name="OPTIONS"/>
    <eLiterals name="TRACE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StringHttpRequest" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="enumeration" value="GET POST HEAD URL OPTIONS TRACE"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
