<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="https://org/eclipse/cmmnmetamodel" nsPrefix="org.eclipse.cmmnmetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="CMMNDiagram" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmmnElements" lowerBound="1"
        upperBound="-1" eType="#//CMMNElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseFile" eSuperTypes="#//CMMNElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Case" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="casefile" lowerBound="1"
        eType="#//CaseFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" lowerBound="1"
        upperBound="-1" eType="#//Stage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stage" eSuperTypes="#//PlanItemDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//PlanItemDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskType" eType="#//TaskType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskRole" eType="#//TaskRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorators" upperBound="-1"
        eType="#//Decorator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventListener" eSuperTypes="#//PlanItemDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Decorator" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sentry" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onPartId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifPart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SentryType" eType="#//SentryType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskRole">
    <eLiterals name="Human"/>
    <eLiterals name="Process" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskType">
    <eLiterals name="Task"/>
    <eLiterals name="DiscretionaryTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SentryType">
    <eLiterals name="Entry"/>
    <eLiterals name="Exit" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlanItemDefinition" eSuperTypes="#//CMMNElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentry" upperBound="-1"
        eType="#//Sentry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimerEventListener" eSuperTypes="#//EventListener">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//TimerExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserEventListener" eSuperTypes="#//EventListener"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimerExpression"/>
</ecore:EPackage>
